version: "3"

services:
  api:
    restart: on-failure
    volumes:
      - ./api:/opt/vision-service/api
    command: >
      uwsgi --wsgi server.main:app
            --http-socket 0.0.0.0:8080
            --python-autoreload 1
            --master
    environment:
      SERVER_APP_CONFIG: server/config/development.py

  model:
    restart: on-failure
    volumes:
      - ./model:/opt/vision-service/model

