version: "3"

services:
  api:
    restart: always
    command: >
      uwsgi --wsgi server.app --http-socket 0.0.0.0:8080
                              --processes 4
                              --threads 2
                              --master

  model:
    restart: always

  redis:
    restart: always

