version: "3"

services:
  api:
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - redis
      - model

  model:
    build: ./model
    command: python server/app.py --batch-size 32
    depends_on:
      - redis

  redis:
    image: redis:5
    volumes:
      - redis_data:/data

volumes:
  redis_data:

